### ISSUE TITLE
How can I use this in practice?

### ISSUE THREAD

**Issue by KasperGroesLudvigsen** [DaoD/INTERS#5]
This seems very interesting! How can I use it in practice? I've read the arxiv paper as well as the info here and on Hugging Face, and I am struggling to understand how I can use an INTERS fine tuned model to improve information retrieval in practice. Could you describe some of the intended use cases? For example, 

1. Can I use it as an alternative to vector search - if so, how? 
2. Is the intention that an INTERS model is used to reformulate a prompt/query? In what scenarios would I want my system to reformulate a user's prompt/query?

**Comment by DaoD** [comment]
Our model is not trained for retrieval stage, because retrieval usually requires an encoder to encode the query and document into vectors and compute their distance as similarity scores. In contrast, our model is trained purely on generation tasks, so it cannot be used for retrieval directly. However, there are several other ways to use our model:
(1) You can use these models for all tasks described in the paper. For example, as you mentioned, the models can be used for query reformulation. Query reforumulation is a common component in building a retrieval system, as uses' input may be ambiguous or vague. 
(2) You can also prompt the models to conduct other IR tasks with proper task descriptions and input formats. Use them just like use other API-based models such as ChatGPT.
(3) You can further fine-tune the models for IR tasks, but I'm not sure if they work better than original LLMs.
